In [1]:
import os
import pandas as pd
import numpy as np

In [9]:
!pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1

## Putting All Together

### Join all dataframes from the features extraction notebooks in a single one called data_std_limit

In [10]:
import pandas as pd

# Path to the Excel file
file_path = 'C:/Users/user/Desktop/PI_project/tcia-diagnosis-data-2012-04-20.xls'

# Read the Excel file
diagnosis_data = pd.read_excel(file_path)

# Display the loaded data
diagnosis_data

,TCIA Patient ID,"Diagnosis at the Patient Level\n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic\n",Diagnosis Method\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response,Primary tumor site for metastatic disease,"Nodule 1\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 1\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 2\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 2\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 3\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 3\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 4\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 4\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 5\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 5\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n
0,LIDC-IDRI-0068,3,4,Head & Neck Cancer,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LIDC-IDRI-0071,3,1,Head & Neck,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LIDC-IDRI-0072,2,4,Lung Cancer,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LIDC-IDRI-0088,3,0,Uterine Cancer,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LIDC-IDRI-0090,2,3,NSCLC,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,LIDC-IDRI-0994,2,3,LUL Large cell CA,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,LIDC-IDRI-1002,2,2,non-small cell carcinoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,LIDC-IDRI-1004,2,3,LUL NSCLC,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,LIDC-IDRI-1010,0,0,lymphoma,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,LIDC-IDRI-1011,3,2,small-cell carcinoma of the tongue,3.0,2.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN

#### std_limit = 0.5

In [11]:
%cd "C:\Users\user\Desktop\PI_project\std_limit_0.5"

C:\Users\user\Desktop\PI_project\std_limit_0.5

In [17]:
features_radiomics_05 = pd.read_csv(r'C:\Users\user\Desktop\PI_project\std_limit_0.5\features_radiomics_2d_0.5.csv')
features_xml_05 = pd.read_csv(r'C:\Users\user\Desktop\PI_project\features_pylidc_0.5.csv')

In [30]:
data = pd.merge(features_xml_05, features_radiomics_05, on='Nodule_id', how='inner')
data_05 = data.merge(diagnosis_data, left_on=data.iloc[:, 1], right_on='TCIA Patient ID', how='left')
data_05.to_csv('C:/Users/user/Desktop/PI_project/data_0.5.csv', index=False)
data_05

,Nodule_id,Patient_id,Subtlety,Internalstructure,Calcification,Sphericity,Margin,Lobulation,Spiculation,Texture,...,"Nodule 1\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 1\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 2\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 2\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 3\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 3\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 4\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 4\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 5\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 5\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n
0,3,LIDC-IDRI-0003,1,1,6,5,2,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10,LIDC-IDRI-0005,3,1,6,3,5,1,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11,LIDC-IDRI-0006,3,1,6,3,5,2,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13,LIDC-IDRI-0006,1,1,6,5,2,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16,LIDC-IDRI-0007,4,1,6,5,2,4,4,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
961,2642,LIDC-IDRI-1008,5,1,3,5,5,1,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
962,2644,LIDC-IDRI-1008,3,1,6,2,3,2,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
963,2645,LIDC-IDRI-1009,3,1,6,5,5,1,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964,2646,LIDC-IDRI-1010,3,1,6,2,5,1,1,5,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965,2650,LIDC-IDRI-1011,1,1,6,4,2,1,1,1,...,3.0,2.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN

#### std_limit = 1.0

In [19]:
%cd "C:\Users\user\Desktop\PI_project\std_limit_1.0"

C:\Users\user\Desktop\PI_project\std_limit_1.0

In [20]:
features_radiomics_10 = pd.read_csv(r'C:\Users\user\Desktop\PI_project\std_limit_1.0\features_radiomics_2d_1.0.csv')
features_xml_10 = pd.read_csv(r'C:\Users\user\Desktop\PI_project\features_pylidc_1.0.csv')

In [29]:
data = pd.merge(features_xml_10, features_radiomics_10, on='Nodule_id', how='inner')
data_10 = data.merge(diagnosis_data, left_on=data.iloc[:, 1], right_on='TCIA Patient ID', how='left')
data_10.to_csv('C:/Users/user/Desktop/PI_project/data_1.0.csv', index=False)
data_10

,Nodule_id,Patient_id,Subtlety,Internalstructure,Calcification,Sphericity,Margin,Lobulation,Spiculation,Texture,...,"Nodule 1\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 1\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 2\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 2\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 3\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 3\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 4\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 4\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 5\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 5\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n
0,2,LIDC-IDRI-0002,2,1,6,5,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,LIDC-IDRI-0003,1,1,6,5,2,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9,LIDC-IDRI-0005,4,1,6,3,5,1,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10,LIDC-IDRI-0005,3,1,6,3,5,1,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,LIDC-IDRI-0006,3,1,6,3,5,2,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651,2642,LIDC-IDRI-1008,5,1,3,5,5,1,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1652,2644,LIDC-IDRI-1008,3,1,6,2,3,2,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1653,2645,LIDC-IDRI-1009,3,1,6,5,5,1,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1654,2646,LIDC-IDRI-1010,3,1,6,2,5,1,1,5,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1655,2650,LIDC-IDRI-1011,1,1,6,4,2,1,1,1,...,3.0,2.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN

#### std_limit = 1.5

In [22]:
%cd "C:\Users\user\Desktop\PI_project\std_limit_1.5"

C:\Users\user\Desktop\PI_project\std_limit_1.5

In [24]:
features_radiomics_15 = pd.read_csv(r'C:\Users\user\Desktop\PI_project\std_limit_1.5\features_radiomics_2d_1.5.csv')
features_xml_15 = pd.read_csv(r'C:\Users\user\Desktop\PI_project\features_pylidc_1.5.csv')

In [28]:
data = pd.merge(features_xml_15, features_radiomics_15, on='Nodule_id', how='inner')
data_15 = data.merge(diagnosis_data, left_on=data.iloc[:, 1], right_on='TCIA Patient ID', how='left')
data_15.to_csv('C:/Users/user/Desktop/PI_project/data_1.5.csv', index=False)
data_15

,Nodule_id,Patient_id,Subtlety,Internalstructure,Calcification,Sphericity,Margin,Lobulation,Spiculation,Texture,...,"Nodule 1\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 1\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 2\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 2\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 3\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 3\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 4\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 4\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n,"Nodule 5\nDiagnosis at the Nodule Level \n0=Unknown\n1=benign or non-malignant disease\n2= malignant, primary lung cancer\n3 = malignant metastatic)\n",Nodule 5\nDiagnosis Method at the Nodule Level\n0 = unknown\n1 = review of radiological images to show 2 years of stable nodule\n2 = biopsy\n3 = surgical resection\n4 = progression or response\n
0,1,LIDC-IDRI-0001,5,1,6,3,3,3,4,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,LIDC-IDRI-0002,2,1,6,5,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,LIDC-IDRI-0003,1,1,6,5,2,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,LIDC-IDRI-0003,5,1,6,3,3,2,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,LIDC-IDRI-0003,4,1,6,3,4,1,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2435,2645,LIDC-IDRI-1009,3,1,6,5,5,1,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2436,2646,LIDC-IDRI-1010,3,1,6,2,5,1,1,5,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2437,2648,LIDC-IDRI-1011,5,1,6,5,5,4,1,5,...,3.0,2.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
2438,2649,LIDC-IDRI-1011,3,1,6,4,3,1,1,5,...,3.0,2.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
2439,2650,LIDC-IDRI-1011,1,1,6,4,2,1,1,1,...,3.0,2.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN